### ISSUE TITLE
Add ability to add species with greater asymptotic weight to existing params object using addSpecies

### ISSUE THREAD

**Issue by SamikDatta** [sizespectrum/mizerExperimental#13]
At present you are unable to add a species to an existing `params` object with a higher value for `w_inf` using the `addSpecies` function. If you do, you get the error:

`Error in emptyParams(species_params, gear_params, no_w = no_w, min_w = min_w,  : 
  Some of your species have an maximum size larger than max_w:`

(followed by the species name).

**Comment by gustavdelius** [comment]
Nice suggestion for an improvement.

If the original params object was created using just the information from its `species_params`, `gear_params` and `resource_params` slots, then extending the size range will be easy: simply join the old and new `species_params`, `gear_params` , `interaction` and `initial_effort` and then call `newMultispeciesParams()` to create a params object from scratch based on that information. If however the params object holds user-calculated rates, then these would be lost by that approach.

The current `addSpecies()` code therefore keeps those user-calculated rates and puts them back into the corresponding part of the rates produced by `newMultispeciesParams`. The same approach should still work for those rates that are zero or irrelevant anyway outside the size range of a species. I think just the feeding kernel slots would be more difficult, so I wouldn't bother with that. There won't be many users who have written their own feeding kernel and want to later add species outside the size range. We can just issue an error message in that edge case.

So please go ahead and implement it.

**Comment by SamikDatta** [comment]
Hi Gustav, apologies, I had not spotted this response. I'll try and get to it sometime this week.

**Comment by gustavdelius** [comment]
To expand a bit on the previous post: the changes needed in `addSpecies()` are:

- [ ]  If any of the new species has a `w_inf` larger than the `max_w` of the previous params object, we need to determine a new `max_w` and `no_w` such that `max_w` is just larger than the largest `w_inf` and such that the start of the new `w` grid agrees with the previous grid. This `max_w` and `no_w` should then be passed to `newMultispeciesParams()`.

- [ ]  Where values are copied over from the previous params object, they need to be directed to the correct entries in the larger arrays in the new params object.

**Comment by SamikDatta** [comment]
Hi Gustav - I've made some good progress on this issue. Could I ask a question - what is the easiest way to run `newMultispeciesParams` on the original `params` object, just with an updated `w` vector, but remembering any manual inputs that the user may have originally specified? I am manually extending some vectors and matrices at present, but I think it would be more sensible (and reliable) to use the functions in _mizer_ to do this.

**Comment by gustavdelius** [comment]
Hi Samik, there is no function for copying over the values from a smaller MizerParams object to a larger one. Currently the code for doing the copying from an object with fewer species to an object with more species is contained in the body of the `addSpecies()` function. You would need to extend that code to also handle the fact that the size dimension has gotten larger.
