### ISSUE TITLE
Allow user to call `project()` with a stopping condition

### ISSUE THREAD

**Issue by gustavdelius** [sizespectrum/mizerExperimental#14]
Currently the user can control the length of a simulation with the `t_max` argument to `project()`. Sometimes users may want to run the simulation only long enough until some feature they are interested in does not change much any more. In fact, mizer itself would like that feature. For example `steady()` currently has to call `project()` repeatedly for a small number of years in order to be able to insert its checks of whether the simulation is close enough to steady state. It would be nicer if it could just pass a function to `project()` that is run at fixed intervals during the projection. If the function returns `TRUE` the projection is stopped at that time.

**Comment by juliablanchard** [comment]
Thanks @gustavdelius,  a function like projectToSteady() which would allow the projection to stop when it is "close enough" to steady state, would be really helpful!

**Comment by gustavdelius** [comment]
@juliablanchard, the new `projectToSteady()` function speeds up the grid search quite a lot, see https://rpubs.com/gustav/649236

**Comment by juliablanchard** [comment]
Thank you @gustavdelius! I will check this out!

________________________________
