### ISSUE TITLE
tuneParams shiny app not functioning...

### ISSUE THREAD

**Issue by SamikDatta** [sizespectrum/mizerExperimental#2]
The module seems to have broken with recent updates. Trying to play with the North Sea parameters:

`tuneParams(NS_Params)`

There is an error on the left hand box, reading:
**Error:** missing value where TRUE/FALSE needed.

This prevents us from modifying parameters in the shiny app.

**Comment by gustavdelius** [comment]
Hi Samik. Thanks for reporting. Sorry it took me a while to get to this.
