### ISSUE TITLE
Adding plots for comparing model and observed biomasses...

### ISSUE THREAD

**Issue by SamikDatta** [sizespectrum/mizerExperimental#22]
I have code written to plot the biomass at the end of a model run, compared to empirical biomass entered as the 'biomass_observed' column in the mizerparams object. The two plots are:

1. plotting model biomass against empirical biomass, on a log10 scale, with the Pearson correlation coefficient calculated in the title.
2. plotting model biomass as fraction of empirical biomass, with the total difference between the two over all species in the model.

**Comment by gustavdelius** [comment]
Thank you @SamikDatta . I am very interested in seeing those plots. Could you create an R Markdown document showing some example plots and publish it to RPubs (you do that by first hitting the Preview button and then, on the preview window, hitting the "Publish" button and selecting RPubs) and then paste the link here?

**Comment by gustavdelius** [comment]
I needed just such a function in the `tuneParams()` shiny gadget. I have extracted the code from that gadget and put it into a new function `plotBiomassVsSpecies()`. It is not a very well thought out plot and I am excited to see it replaced by @SamikDatta with his own code. Also :

- [ ] It should allow a MizerSim object as its argument, not only a MizerParams object
- [ ] It needs roxygen documentation
- [ ] It needs tests
- [ ] It needs to implement more arguments to be in line with other mizer plot functions, for example a `species` argument.

**Comment by gustavdelius** [comment]
Once we have a good `plotBiomassVsSpecies()` plot, we can use similar code to produce a similar `plotYieldVsSpecies()` plot. The one that is currently in the `tuneParams()` gadget is not good.

**Comment by SamikDatta** [comment]
Hi @gustavdelius , I have built a basic RPubs document to show the two functions I have made. Please have a look and see what you think - I'm happy to change these functions to be more in line with the other mizer plotting functions already available.

https://rpubs.com/samikdatta/801157

**Comment by gustavdelius** [comment]
I like your plots very much. Can you make a pull request that contains the functions as they are? I can then comment on them. Thanks @SamikDatta.

**Comment by SamikDatta** [comment]
Hi Gustav. I can't add files (I get a message saying, 'Uploads are disabled. File uploads require push access to this repository.') Should I just include them in the file 'plotBiomassVsSpecies.R', or should I do something else?

**Comment by gustavdelius** [comment]
Hi @SamikDatta, many thanks for your hard work on this. I have now merged it into mizerExperimental. I will play a bit more with it, in particular integrate it into `tuneParams()`, but I think it is ready for prime time. So I think we should include it in the next release of mizer.

One thing I still want to do:

- [ ] create proper testthat tests and then delete 'inst/plotBiomassObservedVsModelTest.R'.

**Comment by SamikDatta** [comment]
Hi Gustav,

Thanks very much for all your work on this. I didn't realise there would still be so much for you to finish off, I appreciate the time you put into it. I'll look over the changes you made and try  to learn from them for future contributions.

I will work on making tests and replacing the file in the 'inst' folder once this is done. Just to check - does it matter if the test functions produce plots, or should they all be strictly arithmetic (i.e. expect_identical and the like)?

Cheers,
Samik.

**Comment by gustavdelius** [comment]
I think I would create one plot with some bells and whistles and check that with `expect_snapshot()`. Then I would do the tests that are easy to do on the basis of the data frame returned with `return_data = TRUE` with `expect_identical()` and the like.
